### ISSUE TITLE
login screen is not optimized for landscape mode

### ISSUE THREAD

**Issue by parth181195** [cerebro-iiitv/cerebro-flutter#34]
we should disable landscape mode if we are not planning to provide support for it.

![screenshot_20181228_095204](https://user-images.githubusercontent.com/17850142/50502611-93053c00-0a86-11e9-8509-5884e072bfba.jpg) 

```dart
void main() {
  SystemChrome.setPreferredOrientations(
          [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])
      .then((orientation) => runApp(MyApp()));
}
```

the above piece of code should fix the orientation to portrait mode

**Comment by aashutoshrathi** [comment]
@yashLadha your views?
Should we disable it or rather provide support?

**Comment by yashLadha** [comment]
Maybe we can make the Login Page responsive for landscape mode. @aashutoshrathi
