### ISSUE TITLE
Add Firebase OAuth

### ISSUE THREAD

**Issue by aashutoshrathi** [cerebro-iiitv/cerebro-flutter#5]

**Comment by yashLadha** [comment]
What is the issue? @aashutoshrathi

**Comment by aashutoshrathi** [comment]
Yes, we will add it after Realtime DBMS.

**Comment by yashLadha** [comment]
Thought of taking it forward and then add it afterwards.

**Comment by aashutoshrathi** [comment]
User:
   int id,
   String name,
   String img_url

**Comment by aashutoshrathi** [comment]
Yes, routing to main app.
